language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
  - gem install rubocop
script:
  - rubocop --config=$(brew --repo)/Library/.rubocop.yml iwyu.rb
  - brew audit iwyu
  - brew install -v iwyu
  - brew test iwyu
